### ISSUE TITLE
Use WP-CLI

### ISSUE THREAD

**Issue by joellobo1234** [adisharma96/linuxprojects#1]
Using WP-CLI can cut down your efforts.

Please move all WordPress related part to https://wp-cli.org/

When you are done close this issue via Github commit.

Also, please share your contact details on hr@rtcamp.com

**Comment by adisharma96** [comment]
Hi,
Can you just explain what i need to due with the stuff that u have mentioned..

**Comment by adisharma96** [comment]
hi,
can you just let me know what i exactly have to to.
Due to the voice lagging problem,i was'nt able to understand everything
clearly

**Comment by adisharma96** [comment]
Hi,
 I have uploaded a new script that makes use of wp-cli for wordpress installation.
Please check.
the filename is: wordpresscli-installer
